# Generated by Django 4.1.5 on 2023-02-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('car_pic', models.ImageField(upload_to='', verbose_name='Image')),
                ('engine_size', models.CharField(max_length=200, verbose_name='Engine Size')),
                ('engine_configuration', models.CharField(max_length=20, verbose_name='Engine Configuration')),
                ('horsepower', models.CharField(max_length=20, verbose_name='Horse Power')),
                ('torque', models.CharField(max_length=20, verbose_name='Torque')),
                ('transmission', models.CharField(max_length=50, verbose_name='Transmission')),
                ('production_year', models.DateField(verbose_name='Year')),
            ],
        ),
    ]
