# Generated by Django 4.1.5 on 2023-02-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=200)),
                ('image_path', models.ImageField(upload_to='', verbose_name='Image')),
                ('selected_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.car')),
            ],
        ),
    ]
