# Generated by Django 4.1.5 on 2023-02-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_cargallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarGallery',
        ),
    ]
