# Generated by Django 4.1.5 on 2023-02-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_delete_cargallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='car_model',
        ),
    ]
