# Generated by Django 4.1.5 on 2023-02-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_model_car_car_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='model',
        ),
    ]
