# Generated by Django 4.1.5 on 2023-02-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_car_model_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_pics', models.ImageField(upload_to='', verbose_name='Image')),
                ('path_name', models.CharField(max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.car')),
            ],
        ),
    ]
